{
    'On a scale of 1 - 5, where 1 is "None" and 5 is "A Lot", how many empty beer or liquor bottles are visible in streets, yards, or alleys?': "Amount of Beer/Liquor Bottles (1 to 5 scale)",
    'On a scale of 1 - 5, where 1 is "None" and 5 is "A Lot",  how many cigarette or cigar butts or discarded cigarette packages  are on the sidewalk or in the gutters? ': "Amount of Cigarette/Cigar Butts (1 to 5 scale)",
    'On a scale of 1 - 5, where 1 is "None" and 5 is "A Lot",  how many condoms are present on the sidewalk, in the gutters, or street of block face? ': "Amount of Condoms (1 to 5 scale)",
    'On a scale of 1 - 5, where 1 is "None" and 5 is "A Lot", how much garbage, litter, or broken glass in the street or on the sidewalks? ': "Amount of Garbage (1 to 5 scale)",
    ' Are there abandoned cars in the neighborhood? How many do you see? ': "Abandoned Cars (Y?N)",
    'On a scale of 1-5 where 1 is "Friendly Responses / Greetings / Helpful" and 5 is "Treated with Suspicion", How were you regarded by the people in the block face?': "Treatment (1 (Friendly) to 5 (Suspicion) scale)",
    'On a scale of 1 - 4, where 1 is "Very well kept / good condition" and 4 is "Poor / badly deteriorated condition", in general, how would you rate the condition of buildings on the block face? (includes residential buildings, recreational facilities, manufacturing plants, business / industrial headquarters, etc)': "Condition of Buildings (1 (Good) to 4 (Poor) scale)",
    'Is there graffiti or evidence of graffiti that has been painted over on buildings, signs, or walls? (Questions 22-23)': "Graffiti (Y/N)",
    'On a scale of 1 - 4, where 1 is "No fencing" and 4 is "High mesh fencing with barbed wire or spiked tops", is there fencing and what kind? (includes all property)': "Fenching (1 (None) to 4 (High mesh) scale)",
    'Are any commercial/residential buildings being renovated?': "Renovations (Y/N)",
    'What kinds of establishments are there on the block face? Select all that apply.': "Types of Establishments",
    'On a scale of 1-3, where 1 is "Few or none" and 3 is a "Most/all of it", how many trees are linking the street of the block face? ': "Amount of Trees Linked the Block Fence (1 (Few) to 3 (Most) scale)",
    'Is there public transportation available in the block face? ': "Public Transporation Available (Y/N)",
    'Are private security guards visible?': "Private Security Visible (Y/N)",
    'Is there a police officer visible? ': "Police Visible (Y/N)",
    'Full Address of Block Face in Image #1 (Street Number, Street Name, City, State, Zip Code). E.g.: 2128 Oxford Street, Berkeley, CA, 94704.': "Image #1 Address",
    'Full Address of Block Face in Image #2 (Street Number, Street Name, City, State, Zip Code). E.g.: 2128 Oxford Street, Berkeley, CA, 94704.': "Image #2 Address",
    'Full Address of Block Face in Image #3 (Street Number, Street Name, City, State, Zip Code). E.g.: 2128 Oxford Street, Berkeley, CA, 94704.': "Image #3 Address",
    'Full Address of Block Face in Image #4 (Street Number, Street Name, City, State, Zip Code). E.g.: 2128 Oxford Street, Berkeley, CA, 94704.': "Image #4 Address",
    'Full Address of Block Face in Image #5 (Street Number, Street Name, City, State, Zip Code). E.g.: 2128 Oxford Street, Berkeley, CA, 94704.': "Image #5 Address",
}